[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://movie-search-aleksey-vl-ivanov.netlify.app/*"
  to = "https://movie-search.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://movie-search-aleksey-vl-ivanov.netlify.app/*"
  to = "https://movie-search.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://movie-search.aleksey-vl-ivanov.com/*"
  to = "https://movie-search.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true
